//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "aftercare_signups")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub booking_id: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub email: Option<String>,
    pub created_at: Option<DateTime>,
    #[sea_orm(
        belongs_to,
        from = "booking_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub bookings: HasOne<super::bookings::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
