//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "artist_booking_history")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub artist_id: Option<i64>,
    pub booking_request_id: Option<i64>,
    pub appointment_date: Option<Date>,
    #[sea_orm(column_type = "Text", nullable)]
    pub start_time: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub end_time: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub status: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub notes: Option<String>,
    #[sea_orm(column_type = "Float", nullable)]
    pub final_price: Option<f32>,
    pub created_at: Option<DateTime>,
    #[sea_orm(
        belongs_to,
        from = "artist_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub artists: HasOne<super::artists::Entity>,
    #[sea_orm(
        belongs_to,
        from = "booking_request_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub booking_requests: HasOne<super::booking_requests::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
