//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "artists")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub name: Option<String>,
    pub location_id: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub social_links: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub email: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub phone: Option<String>,
    pub years_experience: Option<i64>,
    pub styles_extracted: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub bio: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub instagram_handle: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub availability_status: Option<String>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub shop_validated: Option<bool>,
    #[sea_orm(has_many)]
    pub artist_availabilities: HasMany<super::artist_availability::Entity>,
    #[sea_orm(has_many)]
    pub artist_booking_histories: HasMany<super::artist_booking_history::Entity>,
    #[sea_orm(has_one)]
    pub artist_pricing: HasOne<super::artist_pricing::Entity>,
    #[sea_orm(has_many)]
    pub artist_questionnaires: HasMany<super::artist_questionnaires::Entity>,
    #[sea_orm(has_one)]
    pub artist_subscriptions: HasOne<super::artist_subscriptions::Entity>,
    #[sea_orm(has_many)]
    pub booking_requests: HasMany<super::booking_requests::Entity>,
    #[sea_orm(has_many)]
    pub bookings: HasMany<super::bookings::Entity>,
    #[sea_orm(has_many)]
    pub business_hours: HasMany<super::business_hours::Entity>,
    #[sea_orm(has_many)]
    pub client_match_impressions: HasMany<super::client_match_impressions::Entity>,
    #[sea_orm(has_many)]
    pub users: HasMany<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
