//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "artists_images")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub short_code: Option<String>,
    pub artist_id: Option<i64>,
    pub post_date: Option<i64>,
    pub validated: Option<bool>,
    pub active: Option<bool>,
    pub admin_reviewed: Option<bool>,
    #[sea_orm(has_many)]
    pub image_style_llm_recommendations: HasMany<super::image_style_llm_recommendations::Entity>,
    #[sea_orm(has_many)]
    pub user_favorites: HasMany<super::user_favorites::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
