//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "artist_subscriptions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    #[sea_orm(unique)]
    pub artist_id: Option<i64>,
    pub tier_id: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub status: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub payment_method: Option<String>,
    pub subscription_start: Option<DateTime>,
    pub subscription_end: Option<DateTime>,
    pub last_payment: Option<DateTime>,
    pub next_payment: Option<DateTime>,
    #[sea_orm(
        belongs_to,
        from = "artist_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub artists: HasOne<super::artists::Entity>,
    #[sea_orm(
        belongs_to,
        from = "tier_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub subscription_tiers: HasOne<super::subscription_tiers::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
