//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "artists_images_styles")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique_key = "artists_images_styles_artists_images_id_style_id_key")]
    pub artists_images_id: Option<i64>,
    #[sea_orm(unique_key = "artists_images_styles_artists_images_id_style_id_key")]
    pub style_id: Option<i64>,
    pub is_admin_corrected: Option<bool>,
    pub corrected_by: Option<i64>,
    pub corrected_at: Option<DateTime>,
    #[sea_orm(
        belongs_to,
        from = "corrected_by",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub users: HasOne<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
