//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "artists_styles")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique_key = "artists_styles_artist_id_style_id_key")]
    pub style_id: Option<i64>,
    #[sea_orm(unique_key = "artists_styles_artist_id_style_id_key")]
    pub artist_id: Option<i64>,
}

impl ActiveModelBehavior for ActiveModel {}
