//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "artist_availability")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub artist_id: Option<i64>,
    pub day_of_week: Option<i64>,
    pub specific_date: Option<Date>,
    #[sea_orm(column_type = "Text", nullable)]
    pub start_time: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub end_time: Option<String>,
    pub is_available: Option<bool>,
    pub is_recurring: Option<bool>,
    pub created_at: Option<DateTime>,
    #[sea_orm(
        belongs_to,
        from = "artist_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub artists: HasOne<super::artists::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
