//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "artist_pricing")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    #[sea_orm(unique)]
    pub artist_id: Option<i64>,
    #[sea_orm(column_type = "Float", nullable)]
    pub hourly_rate: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub minimum_price: Option<f32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub price_range: Option<String>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    #[sea_orm(
        belongs_to,
        from = "artist_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub artists: HasOne<super::artists::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
