//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "artist_questionnaires")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub artist_id: Option<i64>,
    pub question_id: Option<i64>,
    pub is_required: Option<bool>,
    pub display_order: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub custom_options: Option<String>,
    pub is_enabled: Option<bool>,
    #[sea_orm(
        belongs_to,
        from = "artist_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub artists: HasOne<super::artists::Entity>,
    #[sea_orm(
        belongs_to,
        from = "question_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub questionnaire_questions: HasOne<super::questionnaire_questions::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
