//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "booking_requests")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub artist_id: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub client_name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub client_email: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub client_phone: Option<String>,
    pub requested_date: Option<Date>,
    #[sea_orm(column_type = "Text", nullable)]
    pub requested_start_time: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub requested_end_time: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub tattoo_description: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub placement: Option<String>,
    #[sea_orm(column_type = "Float", nullable)]
    pub size_inches: Option<f32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub reference_images: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub message_from_client: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub status: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub artist_response: Option<String>,
    #[sea_orm(column_type = "Float", nullable)]
    pub estimated_price: Option<f32>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    #[sea_orm(column_type = "Text", nullable)]
    pub decline_reason: Option<String>,
    pub suggested_date: Option<Date>,
    #[sea_orm(column_type = "Text", nullable)]
    pub suggested_start_time: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub suggested_end_time: Option<String>,
    #[sea_orm(has_many)]
    pub artist_booking_histories: HasMany<super::artist_booking_history::Entity>,
    #[sea_orm(
        belongs_to,
        from = "artist_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub artists: HasOne<super::artists::Entity>,
    #[sea_orm(has_many)]
    pub booking_messages: HasMany<super::booking_messages::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
