//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "bookings")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub artist_id: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub client_name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub client_email: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub client_phone: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub placement: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub size_inches: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub notes: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub image_path: Option<String>,
    pub booking_date: Option<Date>,
    #[sea_orm(column_type = "Text", nullable)]
    pub status: Option<String>,
    pub created_at: Option<DateTime>,
    #[sea_orm(has_many)]
    pub aftercare_signups: HasMany<super::aftercare_signups::Entity>,
    #[sea_orm(
        belongs_to,
        from = "artist_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub artists: HasOne<super::artists::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
