//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "booking_messages")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub booking_request_id: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub sender_type: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub message: Option<String>,
    pub created_at: Option<DateTime>,
    #[sea_orm(
        belongs_to,
        from = "booking_request_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub booking_requests: HasOne<super::booking_requests::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
