//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "cities")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub state_code: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub state_name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub city: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub county: Option<String>,
    #[sea_orm(column_type = "Float", nullable)]
    pub latitude: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub longitude: Option<f32>,
}

impl ActiveModelBehavior for ActiveModel {}
