//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "client_match_impressions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub session_id: Option<i64>,
    pub artist_id: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub impression_type: Option<String>,
    pub created_at: Option<DateTime>,
    #[sea_orm(
        belongs_to,
        from = "artist_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub artists: HasOne<super::artists::Entity>,
    #[sea_orm(
        belongs_to,
        from = "session_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub client_quiz_sessions: HasOne<super::client_quiz_sessions::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
