//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "client_quiz_sessions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub style_preference: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub body_placement: Option<String>,
    pub pain_tolerance: Option<i64>,
    #[sea_orm(column_type = "Float", nullable)]
    pub budget_min: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub budget_max: Option<f32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub vibe_preference: Option<String>,
    pub created_at: Option<DateTime>,
    #[sea_orm(has_many)]
    pub client_match_impressions: HasMany<super::client_match_impressions::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
