//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "county_boundaries")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Float", nullable)]
    pub low_lat: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub low_long: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub high_lat: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub high_long: Option<f32>,
    pub date_utc_last_ingested: Option<i64>,
}

impl ActiveModelBehavior for ActiveModel {}
