//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "error_logs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub error_type: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub error_level: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub error_message: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub error_stack: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub url_path: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub user_agent: Option<String>,
    pub user_id: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub session_id: Option<String>,
    pub timestamp: Option<DateTime>,
    #[sea_orm(column_type = "Text", nullable)]
    pub request_headers: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub additional_context: Option<String>,
}

impl ActiveModelBehavior for ActiveModel {}
