//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "image_style_llm_recommendations")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique_key = "image_style_llm_recommendations_artists_images_id_style_id_key")]
    pub artists_images_id: i64,
    #[sea_orm(unique_key = "image_style_llm_recommendations_artists_images_id_style_id_key")]
    pub style_id: i64,
    #[sea_orm(column_type = "Double", nullable)]
    pub confidence_score: Option<f64>,
    pub recommended_at: Option<DateTime>,
    #[sea_orm(
        belongs_to,
        from = "artists_images_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub artists_images: HasOne<super::artists_images::Entity>,
    #[sea_orm(
        belongs_to,
        from = "style_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub styles: HasOne<super::styles::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
