//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "locations")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub city: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub county: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub state: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub country_code: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub postal_code: Option<String>,
    pub is_open: Option<i16>,
    #[sea_orm(column_type = "Text", nullable)]
    pub address: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub category: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub website_uri: Option<String>,
    #[sea_orm(column_type = "Float", nullable)]
    pub lat: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub long: Option<f32>,
    pub is_person: Option<i64>,
    #[sea_orm(column_name = "_id", column_type = "Text", nullable, unique)]
    pub source_id: Option<String>,
    pub is_scraped: Option<i64>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
}

impl ActiveModelBehavior for ActiveModel {}
