//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "openai_api_costs")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub action: Option<String>,
    pub count: Option<i64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub avg_cost: Option<f64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub model: Option<String>,
    #[sea_orm(column_type = "Double", nullable)]
    pub total_cost: Option<f64>,
}

impl ActiveModelBehavior for ActiveModel {}
