//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "questionnaire_questions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub question_type: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub question_text: Option<String>,
    pub is_default: Option<bool>,
    #[sea_orm(column_type = "Text", nullable)]
    pub options_data: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub validation_rules: Option<String>,
    pub created_at: Option<DateTime>,
    #[sea_orm(has_many)]
    pub artist_questionnaires: HasMany<super::artist_questionnaires::Entity>,
    #[sea_orm(has_many)]
    pub booking_questionnaire_responses: HasMany<super::booking_questionnaire_responses::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
