//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "recurring_rules")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub artist_id: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub rule_type: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub pattern: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub action: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub start_time: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub end_time: Option<String>,
    pub active: Option<bool>,
    #[sea_orm(column_type = "Text", nullable)]
    pub created_at: Option<String>,
}

impl ActiveModelBehavior for ActiveModel {}
