//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "reddit_scrape_cities")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(
        column_type = "Text",
        unique_key = "reddit_scrape_cities_city_state_key"
    )]
    pub city: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "reddit_scrape_cities_city_state_key"
    )]
    pub state: String,
    pub last_scraped_at: Option<DateTime>,
    #[sea_orm(column_type = "Text", nullable)]
    pub status: Option<String>,
    pub posts_found: Option<i32>,
    pub artists_added: Option<i32>,
    pub artists_updated: Option<i32>,
    pub artists_pending: Option<i32>,
    pub artists_added_from_shop_bios: Option<i32>,
    pub shops_scraped: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub error_message: Option<String>,
}

impl ActiveModelBehavior for ActiveModel {}
