//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "reddit_artists_pending")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub reddit_post_url: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub artist_name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub instagram_handle: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub shop_name_mentioned: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub city: String,
    #[sea_orm(column_type = "Text")]
    pub state: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub post_context: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub match_type: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub status: Option<String>,
    pub created_at: Option<DateTime>,
    pub reviewed_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    #[sea_orm(column_type = "Text", nullable)]
    pub shop_processing_status: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub processing_notes: Option<String>,
}

impl ActiveModelBehavior for ActiveModel {}
