//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "scrape_actions")]
pub struct Model {
    pub location_id: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub action: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub timestamp: Option<String>,
}

impl ActiveModelBehavior for ActiveModel {}
