//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "state_boundaries")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub state_name: String,
    #[sea_orm(column_type = "Text")]
    pub state_code: String,
    #[sea_orm(column_type = "Float")]
    pub low_long: f32,
    #[sea_orm(column_type = "Float")]
    pub low_lat: f32,
    #[sea_orm(column_type = "Float")]
    pub high_long: f32,
    #[sea_orm(column_type = "Float")]
    pub high_lat: f32,
}

impl ActiveModelBehavior for ActiveModel {}
