//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "subscription_tiers")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub tier_name: Option<String>,
    pub tier_level: Option<i64>,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))", nullable)]
    pub price_monthly: Option<Decimal>,
    #[sea_orm(column_type = "Text", nullable)]
    pub features_json: Option<String>,
    pub created_at: Option<DateTime>,
    #[sea_orm(has_many)]
    pub artist_subscriptions: HasMany<super::artist_subscriptions::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
