//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "user_favorites")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique_key = "idx_16631_sqlite_autoindex_user_favorites_1")]
    pub user_id: Option<i64>,
    #[sea_orm(unique_key = "idx_16631_sqlite_autoindex_user_favorites_1")]
    pub artists_images_id: Option<i64>,
    pub created_at: Option<DateTime>,
    #[sea_orm(
        belongs_to,
        from = "artists_images_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub artists_images: HasOne<super::artists_images::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
