//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

use super::sea_orm_active_enums::UserRole;
use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub first_name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub last_name: Option<String>,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub email: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub phone: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub password_hash: Option<String>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub is_active: Option<bool>,
    pub role: UserRole,
    pub artist_id: Option<i64>,
    pub is_verified: Option<bool>,
    pub last_login: Option<DateTime>,
    #[sea_orm(
        belongs_to,
        from = "artist_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub artists: HasOne<super::artists::Entity>,
    #[sea_orm(has_many)]
    pub artists_images_styles: HasMany<super::artists_images_styles::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
